### ISSUE TITLE
Push batch tracing data in a shutdown hook

### ISSUE THREAD

**Issue by benas** [spring-cloud-samples/spring-cloud-sleuth-samples#13]
Currently, the batch sample contains a [`Thread.sleep`](https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/blob/main/batch/src/main/java/com/example/sleuthsamples/BatchApplication.java#L63) to ensure that tracing data is successfully reported.

Is there a way to perform the final push in a shutdown hook so that client code is not required to call this `Thread.sleep`?

**Comment by marcingrzejszczak** [comment]
This is no longer relevant - fixed via https://github.com/spring-cloud/spring-cloud-sleuth/pull/2036
